name: Fetch and Commit robots.txt
# https://darkvisitors.com/docs/robots-txt

on:
  schedule:
    - cron: "55 2 * * *"
  workflow_dispatch:  # Allow manual triggers

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Dark Visitors robots.txt
      uses: valrus/dark-visitors-robots@v1.3.0
      with:
        access-token: ${{ secrets.DARK_VISITORS_ACCESS_TOKEN }}
